### PR TITLE
Scatter QC Plots

### PR DESCRIPTION
**Pull request by helrick**
all features for demo should be included except for the before/after count tiles (will add those on new branch).

### CODE REVIEW

**Comment by suluxan** [comment]
* grey to purple for QC as well

**Comment by suluxan** [comment]
* also pink (min) to purple (max) for metadata - darker makes sense for higher

**Comment by suluxan** [comment]
* bug when selecting qc tsne and then going back to menu and then back to qc (buggy qc violin)

**Comment by suluxan** [comment]
oh! also tsne -> umap for the QC tsnes

**Comment by helrick** [comment]
> * oh! also tsne -> umap for the QC tsnes

already in there (f9ae5f7cb5652bb0824d09e4bbc1fa71904b6451)

**Comment by helrick** [comment]
> * bug when selecting qc tsne and then going back to menu and then back to qc (buggy qc violin)

fixed in e01419b39b8b17d4c8a2c53c88e6a7473accbb9d

**Pull request merged**
